@Rekentool_HostAddress = https://localhost:7122

POST {{Rekentool_HostAddress}}/api/Vruchtgebruik/
Content-Type: application/json
{
  "eigendomswaarde": 100000,
  "leeftijd": 35,
  "geslacht": "Vrouw",
  "berekeningsmethode": "EenLeven"
}

###
